### PR TITLE
The lab loop is solved-part(1).

### PR DESCRIPTION
**Pull request by Sufana-Aljawi**

### CODE REVIEW

**Comment by KhamisAldossari** [comment]
my solution for the bonus was 17 lines and you did it in just 7 lines, Impressive!

**Comment by Sufana-Aljawi** [comment]
> my solution for the bonus was 17 lines and you did it in just 7 lines, Impressive!

Thank you.

**Comment by wijdan-alharbi** [comment]
Great work 👍 , but in the bonus question, it would be more efficient to use the remainder of division to get the even numbers instead of incrementing by 2 each time.

**Comment by Sufana-Aljawi** [comment]
> Great work 👍, but in the bonus question, it would be more efficient to use the remainder of division to get the even numbers instead of incrementing by 2 each time.

Ok, Thank you so much. 👍

**Pull request closed without merging**
